import { Octokit } from '@octokit/rest';
import * as fs from 'fs';
import * as dotenv from 'dotenv';
import { ReasoningResult } from '../llm/locatorReasoner';

dotenv.config();

export interface PRResult {
  prUrl: string;
  branchName: string;
  patchedContent: string;
}

function patchTestFile(
  originalContent: string,
  result: ReasoningResult
): string {
  const oldSelector = result.originalSelector;
  const newSelector = result.suggestedSelector;

  // Replace all occurrences of the old selector in the test file
  const patched = originalContent.split(`'${oldSelector}'`).join(`'${newSelector}'`);
  return patched.split(`"${oldSelector}"`).join(`"${newSelector}"`);
}

function buildPRBody(result: ReasoningResult): string {
  return `## Self-Healing Test Fix

This PR was automatically generated by the Playwright Self-Healer agent.

### What changed
| | Selector |
|---|---|
| **Before** | \`${result.originalSelector}\` |
| **After** | \`${result.suggestedSelector}\` |

### Confidence score
**${result.confidence}%** — ${result.reasoning}

### Fallback options considered
${result.fallbackSelectors.map((s) => `- \`${s}\``).join('\n')}

### Action required
- [ ] Review the selector change looks correct
- [ ] Run the test suite locally to verify
- [ ] Merge if everything looks good

> This PR was opened automatically. Always verify before merging.`;
}

export async function openFixPR(
  testFilePath: string,
  result: ReasoningResult
): Promise<PRResult> {
  const octokit = new Octokit({
    auth: process.env.GITHUB_TOKEN,
  });

  const owner = process.env.GITHUB_OWNER!;
  const repo = process.env.GITHUB_REPO!;
  const branchName = `self-healer/fix-${Date.now()}`;

  console.log('\n Starting GitHub PR automation...');

  // Step 1: Get the latest commit SHA on main
  const { data: refData } = await octokit.git.getRef({
    owner,
    repo,
    ref: 'heads/main',
  });
  const baseSha = refData.object.sha;
  console.log(` Got base SHA: ${baseSha.slice(0, 7)}`);

  // Step 2: Create a new branch
  await octokit.git.createRef({
    owner,
    repo,
    ref: `refs/heads/${branchName}`,
    sha: baseSha,
  });
  console.log(` Created branch: ${branchName}`);

  // Step 3: Get current file content from GitHub
  const { data: fileData } = await octokit.repos.getContent({
    owner,
    repo,
    path: testFilePath,
    ref: 'main',
  });

  if (!('content' in fileData)) {
    throw new Error('Could not retrieve file content from GitHub');
  }

  const originalContent = Buffer.from(fileData.content, 'base64').toString('utf8');
  const patchedContent = patchTestFile(originalContent, result);
  const fileSha = fileData.sha;

  // Step 4: Commit the patched file to the new branch
  await octokit.repos.createOrUpdateFileContents({
    owner,
    repo,
    path: testFilePath,
    message: `fix: self-heal broken selector ${result.originalSelector} → ${result.suggestedSelector}`,
    content: Buffer.from(patchedContent).toString('base64'),
    sha: fileSha,
    branch: branchName,
  });
  console.log(` Committed patched file`);

  // Step 5: Open the PR
  const { data: prData } = await octokit.pulls.create({
    owner,
    repo,
    title: `[Self-Healer] Fix broken selector: ${result.originalSelector}`,
    body: buildPRBody(result),
    head: branchName,
    base: 'main',
  });

  console.log(` PR opened: ${prData.html_url}`);

  return {
    prUrl: prData.html_url,
    branchName,
    patchedContent,
  };
}